#!/usr/bin/lua

-- Check local machine requirements
local requirements = { "openssl", }

for _, v in ipairs(requirements) do
    local subp = io.popen("which " .. v .. " 2>&1")
    local result = subp:read("*a")
    subp:close()

    if string.match(result, "no " .. v .. " in") then
        print("Missing requirement: " .. v)
        return
    end
end

-- Check arguments
if (arg[1] == nil) then
    print("Usage: lua check_ssl.lua <URL>")
    return
end

-- Check input and remove unwanted protocol
local url = arg[1]
url = string.gsub(url, "http://", "", 1)
url = string.gsub(url, "https://", "", 1)

local servername = string.match(url, "[^/]*")

local command = "openssl s_client -showcerts -servername " .. servername ..
                " -connect " .. servername .. ":443 2>/dev/null | openssl x509 -inform pem -noout -text"

os.execute(command)

